const express=require('express');const {z}=require('zod');const {verifyToken,requireRole}=require('../middleware/auth');const repository=require('../modules/operations/repository');const service=require('../modules/operations/service');const {MarketplaceError}=require('../modules/marketplace/errors');const router=express.Router();const adminOnly=[verifyToken,requireRole('admin')];
function respond(error,res){if(error instanceof MarketplaceError)return res.status(error.status).json({error:error.message,code:error.code});console.error(error);return res.status(500).json({error:'Failed'});}function page(input,res){const p=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(20)}).safeParse(input);if(!p.success){res.status(400).json({error:p.error.issues[0].message});return null;}return p.data;}
router.get('/stats',...adminOnly,async(_req,res)=>{try{res.json(await repository.adminStats());}catch(error){respond(error,res);}});
router.get('/users',...adminOnly,async(req,res)=>{const p=page(req.query,res);if(!p)return;try{const input={role:['customer','worker','admin'].includes(req.query.role)?req.query.role:null,search:typeof req.query.search==='string'?req.query.search.slice(0,100):null,suspended:req.query.suspended==='true',limit:p.limit,offset:(p.page-1)*p.limit};const [users,total]=await Promise.all([repository.adminUsers(input),repository.countAdminUsers(input)]);res.json({users,total:total.count,page:p.page,limit:p.limit});}catch(error){respond(error,res);}});
router.get('/users/:id',...adminOnly,async(req,res)=>{try{const user=await repository.adminUser(req.params.id);if(!user)return res.status(404).json({error:'User not found'});res.json(user);}catch(error){respond(error,res);}});
router.put('/users/:id/force-verify',...adminOnly,async(req,res)=>{try{await service.moderateUser({actorId:req.user.id,userId:req.params.id,action:'force_verify',value:req.body.force_verified,reason:req.body.reason});res.json({message:'Updated'});}catch(error){respond(error,res);}});
router.put('/users/:id/verify-nic',...adminOnly,async(req,res)=>{try{await service.moderateUser({actorId:req.user.id,userId:req.params.id,action:'verify_nic',value:req.body.verified,reason:req.body.reason});res.json({message:'Updated'});}catch(error){respond(error,res);}});
router.put('/users/:id/suspend',...adminOnly,async(req,res)=>{try{if(req.params.id===req.user.id)return res.status(400).json({error:'Administrators cannot suspend themselves'});await service.moderateUser({actorId:req.user.id,userId:req.params.id,action:'suspend',value:req.body.suspended,reason:req.body.reason});res.json({message:'Updated'});}catch(error){respond(error,res);}});
router.get('/workers',...adminOnly,async(_req,res)=>{try{res.json(await repository.listAdminWorkers());}catch(error){respond(error,res);}});
router.get('/jobs',...adminOnly,async(req,res)=>{const p=page(req.query,res);if(!p)return;try{const input={status:typeof req.query.status==='string'?req.query.status:null,category:typeof req.query.category==='string'?req.query.category.slice(0,100):null,district:typeof req.query.district==='string'?req.query.district.slice(0,100):null,limit:p.limit,offset:(p.page-1)*p.limit};const [jobs,total]=await Promise.all([repository.listAdminJobs(input),repository.countAdminJobs(input)]);res.json({jobs,total:total.count,page:p.page,limit:p.limit});}catch(error){respond(error,res);}});
router.put('/jobs/:id/flag',...adminOnly,async(req,res)=>{try{await service.flagJob({actorId:req.user.id,jobId:req.params.id,reason:req.body.reason});res.json({message:'Job flagged'});}catch(error){respond(error,res);}});
router.get('/reports',...adminOnly,async(req,res)=>{try{res.json(await repository.listAdminReports(req.query.status||null,req.query.type||null));}catch(error){respond(error,res);}});
router.put('/reports/:id/resolve',...adminOnly,async(req,res)=>{try{await service.resolveReport({actorId:req.user.id,reportId:req.params.id,status:req.body.status,note:req.body.resolution_note});res.json({message:'Report resolved'});}catch(error){respond(error,res);}});
router.get('/categories',...adminOnly,async(_req,res)=>{try{res.json(await repository.listCategoriesAdmin());}catch(error){respond(error,res);}});
router.post('/categories',...adminOnly,async(req,res)=>{if(typeof req.body.name!=='string'||!req.body.name.trim())return res.status(400).json({error:'Name required'});try{res.status(201).json(await repository.insertCategory({name:req.body.name.trim(),icon:req.body.icon||null,parentId:req.body.parent_id||null}));}catch(error){respond(error,res);}});
router.put('/categories/:id',...adminOnly,async(req,res)=>{try{const updated=await repository.updateCategory(req.params.id,{name:req.body.name||null,icon:req.body.icon||null,isActive:typeof req.body.is_active==='boolean'?req.body.is_active:null});if(!updated)return res.status(404).json({error:'Category not found'});res.json({message:'Updated'});}catch(error){respond(error,res);}});
router.delete('/categories/:id',...adminOnly,async(req,res)=>{try{const updated=await repository.updateCategory(req.params.id,{name:null,icon:null,isActive:false});if(!updated)return res.status(404).json({error:'Category not found'});res.json({message:'Category deactivated'});}catch(error){respond(error,res);}});module.exports=router;
