const express = require('express'); const { z } = require('zod'); const repository = require('../modules/identity/repository'); const { maskPhone } = require('../services/contactReveal'); const { NEW_WORKER_MAX_JOBS } = require('../agents/lanes'); const router = express.Router();
const filters = z.object({ category: z.string().trim().max(100).optional(), district: z.string().trim().max(100).optional(), min_rating: z.coerce.number().min(0).max(5).optional(), verified: z.enum(['true', 'false']).optional(), new_only: z.enum(['true', 'false']).optional(), sort: z.enum(['recommended', 'rating', 'jobs', 'newest']).default('recommended'), search: z.string().trim().max(100).optional(), page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(50).default(20) });
function query(schema, input, res) { const parsed = schema.safeParse(input); if (!parsed.success) { res.status(400).json({ error: parsed.error.issues[0].message }); return null; } return parsed.data; }
router.get('/', async (req,res) => { const data=query(filters,req.query,res); if(!data)return; try { const input={category:data.category||null,district:data.district||null,minRating:data.min_rating??null,verified:data.verified==='true',newOnly:data.new_only==='true',newMaxJobs:NEW_WORKER_MAX_JOBS,sort:data.sort,search:data.search||null,limit:data.limit,offset:(data.page-1)*data.limit}; const [workers,total]=await Promise.all([repository.listWorkers(input),repository.countWorkers(input)]); res.json({workers,total:total.count,page:data.page,limit:data.limit}); } catch(error){console.error(error);res.status(500).json({error:'Failed'});} });
router.get('/stats', async (_req, res) => { try { const stats = await repository.publicMarketplaceStats(); res.set('Cache-Control', 'public, max-age=300'); res.json(stats); } catch (error) { console.error(error); res.status(500).json({ error: 'Failed' }); } });
router.get('/:id', async(req,res)=>{try{const worker=await repository.publicWorker(req.params.id);if(!worker)return res.status(404).json({error:'Worker not found'});worker.phone=maskPhone(worker.phone);const profile=await repository.workerProfileId(req.params.id);worker.portfolio_photos=profile?await repository.workerPortfolio(profile.id):[];worker.skills=await repository.workerSkills(req.params.id);res.json(worker);}catch(error){console.error(error);res.status(500).json({error:'Failed'});}});
router.get('/:id/reviews',async(req,res)=>{const data=query(z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(10)}),req.query,res);if(!data)return;try{res.json(await repository.workerReviews(req.params.id,data.limit,(data.page-1)*data.limit));}catch(error){console.error(error);res.status(500).json({error:'Failed'});}});
// Finished jobs, public like the rest of the worker profile.
router.get('/:id/jobs',async(req,res)=>{const data=query(z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(6)}),req.query,res);if(!data)return;try{if(!await repository.publicWorker(req.params.id))return res.status(404).json({error:'Worker not found'});const [jobs,total]=await Promise.all([repository.completedJobs({workerId:req.params.id,limit:data.limit,offset:(data.page-1)*data.limit}),repository.countCompletedJobs({workerId:req.params.id})]);res.json({jobs,total:total.count,page:data.page,limit:data.limit});}catch(error){console.error(error);res.status(500).json({error:'Failed'});}});
module.exports=router;
