const { z }=require('zod');const {withTransaction}=require('../../db/transaction');const repository=require('./repository');const {badRequest,notFound}=require('../marketplace/errors');
const report=z.object({reported_user_id:z.string().uuid().nullable().optional(),job_id:z.string().uuid().nullable().optional(),report_type:z.enum(['inappropriate_job','fake_job','no_show','abusive_behavior','fake_review','price_dispute','other']),description:z.string().trim().min(1).max(10000)}).refine(value=>value.reported_user_id||value.job_id,{message:'A reported user or job is required'});
function parse(schema,input){const result=schema.safeParse(input);if(!result.success)throw badRequest(result.error.issues[0].message);return result.data;}
async function createReport(reporterId,input){const data=parse(report,input);return repository.insertReport({reporterId,reportedUserId:data.reported_user_id||null,jobId:data.job_id||null,type:data.report_type,description:data.description});}
async function readNotification(userId,id){const result=await repository.markNotificationRead(id,userId);if(!result)throw notFound('Notification not found');}
async function moderateUser({actorId,userId,action,value,reason}){if(typeof value!=='boolean')throw badRequest('A boolean value is required');const field=action==='force_verify'?'forceVerified':action==='suspend'?'suspended':'nicVerified';return withTransaction(async({tx})=>{const before=await repository.adminUser(userId);if(!before)throw notFound('User not found');const updated=await repository.updateAdminUser(userId,{forceVerified:null,suspended:null,nicVerified:null,[field]:value,actorId},tx);await repository.insertAudit({actorId,action,entityType:'user',entityId:userId,reason:reason||null,beforeState:before,afterState:updated},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
async function flagJob({actorId,jobId,reason}){return withTransaction(async({tx})=>{const updated=await repository.flagJob(jobId,tx);if(!updated)throw notFound('Job not found');await repository.insertAudit({actorId,action:'flag_job',entityType:'job',entityId:jobId,reason:reason||null,beforeState:null,afterState:updated},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
async function resolveReport({actorId,reportId,status,note}){if(!['dismissed','warned','actioned'].includes(status))throw badRequest('Invalid report resolution status');return withTransaction(async({tx})=>{const updated=await repository.resolveReport(reportId,{actorId,status,note:note||null},tx);if(!updated)throw notFound('Open report not found');await repository.insertNotification({userId:updated.reporter_id,type:'report_updated',title:'Report Updated',body:`Your report has been resolved: ${status}`,meta:{report_id:updated.id}},tx);await repository.insertAudit({actorId,action:'resolve_report',entityType:'report',entityId:reportId,reason:note||null,beforeState:null,afterState:updated},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
module.exports={createReport,flagJob,moderateUser,readNotification,resolveReport};
