const { z }=require('zod');const {withTransaction}=require('../../db/transaction');const repository=require('./repository');const {badRequest,notFound}=require('../marketplace/errors');
const report=z.object({reported_user_id:z.string().uuid().nullable().optional(),job_id:z.string().uuid().nullable().optional(),report_type:z.enum(['inappropriate_job','fake_job','no_show','abusive_behavior','fake_review','price_dispute','other']),description:z.string().trim().min(1).max(10000)}).refine(value=>value.reported_user_id||value.job_id,{message:'A reported user or job is required'});
function parse(schema,input){const result=schema.safeParse(input);if(!result.success)throw badRequest(result.error.issues[0].message);return result.data;}
async function createReport(reporterId,input){const data=parse(report,input);if(data.reported_user_id&&data.reported_user_id===reporterId)throw badRequest('You can’t report yourself');return repository.insertReport({reporterId,reportedUserId:data.reported_user_id||null,jobId:data.job_id||null,type:data.report_type,description:data.description});}
async function readNotification(userId,id){const result=await repository.markNotificationRead(id,userId);if(!result)throw notFound('Notification not found');}
async function moderateUser({actorId,userId,action,value,reason}){if(typeof value!=='boolean')throw badRequest('A boolean value is required');const field=action==='force_verify'?'forceVerified':action==='suspend'?'suspended':'nicVerified';return withTransaction(async({tx})=>{const before=await repository.adminUser(userId);if(!before)throw notFound('User not found');const updated=await repository.updateAdminUser(userId,{forceVerified:null,suspended:null,nicVerified:null,[field]:value,actorId},tx);if(action==='verify_nic'&&value===true&&!before.is_nic_verified)await repository.insertNotification({userId,type:'nic_verified',title:'Identity verified',body:'Your NIC has been verified. A verified badge now appears on your profile.',meta:{}},tx);await repository.insertAudit({actorId,action,entityType:'user',entityId:userId,reason:reason||null,beforeState:before,afterState:updated},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
async function rejectNic({actorId,userId,reason}){const note=typeof reason==='string'?reason.trim():'';if(note.length<3||note.length>500)throw badRequest('A rejection reason is required (3-500 characters)');return withTransaction(async({tx})=>{const before=await repository.adminUser(userId);if(!before)throw notFound('User not found');const updated=await repository.rejectNic(userId,note,tx);if(!updated)throw notFound('Worker not found');await repository.insertNotification({userId,type:'nic_rejected',title:'NIC needs a new photo',body:`Your NIC could not be verified: ${note}. Please upload a new photo from Edit profile.`,meta:{}},tx);await repository.insertAudit({actorId,action:'reject_nic',entityType:'user',entityId:userId,reason:note,beforeState:before,afterState:{id:updated.id,is_nic_verified:updated.is_nic_verified,nic_rejection_reason:updated.nic_rejection_reason}},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
async function flagJob({actorId,jobId,reason}){const note=typeof reason==='string'?reason.trim():'';if(note.length<3||note.length>500)throw badRequest('A reason is required to take a job down (3-500 characters)');return withTransaction(async({tx})=>{const updated=await repository.flagJob(jobId,note,tx);if(!updated)throw notFound('Job not found');await repository.insertNotification({userId:updated.customer_id,type:'job_flagged',title:'Your job was taken down',body:`“${updated.title}” was removed from Fixly: ${note}`,meta:{job_id:jobId}},tx);await repository.insertAudit({actorId,action:'flag_job',entityType:'job',entityId:jobId,reason:reason||null,beforeState:null,afterState:updated},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
async function restoreJob({actorId,jobId,reason}){return withTransaction(async({tx})=>{const updated=await repository.restoreJob(jobId,tx);if(!updated)throw notFound('Taken-down job not found');await repository.insertNotification({userId:updated.customer_id,type:'job_restored',title:'Your job is live again',body:`“${updated.title}” is visible to workers again.`,meta:{job_id:jobId}},tx);await repository.insertAudit({actorId,action:'restore_job',entityType:'job',entityId:jobId,reason:reason||null,beforeState:null,afterState:updated},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
async function resolveDispute({actorId,paymentId,note}){const text=typeof note==='string'?note.trim():'';if(text.length<3||text.length>1000)throw badRequest('Describe how the dispute was resolved (3-1000 characters)');return withTransaction(async({tx})=>{const updated=await repository.resolveDispute(paymentId,{actorId,note:text},tx);if(!updated)throw notFound('Open dispute not found');for(const userId of [updated.customer_id,updated.assigned_worker_id]){await repository.insertNotification({userId,type:'dispute_resolved',title:'Payment dispute closed',body:`Fixly closed the payment dispute for “${updated.job_title}”: ${text}`,meta:{job_id:updated.job_id,payment_id:updated.id}},tx);}await repository.insertAudit({actorId,action:'resolve_dispute',entityType:'payment',entityId:paymentId,reason:text,beforeState:null,afterState:updated},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
async function resolveReport({actorId,reportId,status,note}){if(!['dismissed','warned','actioned'].includes(status))throw badRequest('Invalid report resolution status');return withTransaction(async({tx})=>{const updated=await repository.resolveReport(reportId,{actorId,status,note:note||null},tx);if(!updated)throw notFound('Open report not found');await repository.insertNotification({userId:updated.reporter_id,type:'report_updated',title:'Report Updated',body:`Your report has been resolved: ${status}`,meta:{report_id:updated.id}},tx);await repository.insertAudit({actorId,action:'resolve_report',entityType:'report',entityId:reportId,reason:note||null,beforeState:null,afterState:updated},tx);return updated;},{isolationLevel:'serializable',maxRetries:2});}
module.exports={createReport,flagJob,moderateUser,readNotification,rejectNic,resolveDispute,resolveReport,restoreJob};
